# Code Generated by Sidekick is for learning and experimentation purposes only.
class Parent:
    def greet(self):
        print("Hello from Parent")

class Child(Parent):
    def greet(self):
        print("Hello from Child")

def call_greet(obj):
    obj.greet()  # Works for both Parent and Child

p = Parent()
c = Child()

call_greet(p)  # Hello from Parent
call_greet(c)  # Hello from Child